
GET http://localhost:3000/books

###

GET http://localhost:3000/books/628e4f6990e273cbc813373d

###

GET http://localhost:3000/books/suggestions

###

POST http://localhost:3000/books/new
Content-Type: application/json

{
  "user": "628e2e14694db900fd18dbaa",
  "bookTitle": "String",
  "author": "String", 
  "description": "String", 
  "reason": "String", 
}